import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Language(),
        ]),
      ),
    );
  }
}

class Language extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF0961F5), Color(0xFFFCCB40)],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 428,
                  height: 926,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF0961F5), Color(0xFFFCCB40)],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 69,
                child: Container(
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      const SizedBox(width: 11.79),
                      Text(
                        'Language',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 21,
                          fontFamily: 'Jost',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 129,
                child: Container(
                  width: 360,
                  height: 117,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          'SubCategories:',
                          style: TextStyle(
                            color: Color(0xFF202244),
                            fontSize: 18,
                            fontFamily: 'Jost',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 41,
                        child: Container(
                          width: 340,
                          height: 28,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 312,
                                top: 0,
                                child: Container(
                                  width: 28,
                                  height: 28,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF167F71),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 5,
                                child: Text(
                                  'English (US)',
                                  style: TextStyle(
                                    color: Color(0xFF202244),
                                    fontSize: 15,
                                    fontFamily: 'Mulish',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 89,
                        child: Container(
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Text(
                                'English (UK)',
                                style: TextStyle(
                                  color: Color(0xFF202244),
                                  fontSize: 15,
                                  fontFamily: 'Mulish',
                                  fontWeight: FontWeight.w700,
                                  height: 0,
                                ),
                              ),
                              const SizedBox(width: 224),
                              Container(
                                width: 28,
                                height: 28,
                                decoration: ShapeDecoration(
                                  color: Color(0xFFE8F1FF),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 271,
                child: Text(
                  'All Language',
                  style: TextStyle(
                    color: Color(0xFF202244),
                    fontSize: 18,
                    fontFamily: 'Jost',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 312,
                child: Container(
                  width: 340,
                  height: 28,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 312,
                        top: 0,
                        child: Container(
                          width: 28,
                          height: 28,
                          decoration: ShapeDecoration(
                            color: Color(0xFF167F71),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 5,
                        child: Text(
                          'English (US)',
                          style: TextStyle(
                            color: Color(0xFF202244),
                            fontSize: 15,
                            fontFamily: 'Mulish',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 360,
                child: Container(
                  width: 340,
                  height: 28,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 312,
                        top: 0,
                        child: Container(
                          width: 28,
                          height: 28,
                          decoration: ShapeDecoration(
                            color: Color(0xFFE8F1FF),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 312,
                        top: 0,
                        child: Container(
                          width: 28,
                          height: 28,
                          decoration: ShapeDecoration(
                            color: Color(0xFF167F71),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 5,
                        child: Text(
                          'Arabic',
                          style: TextStyle(
                            color: Color(0xFF202244),
                            fontSize: 15,
                            fontFamily: 'Mulish',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 408,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Hindi',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 274),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 456,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Bengali',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 257),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 504,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Deutsch',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 253),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 552,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Italian',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 266),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 600,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Korean',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 260),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 648,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Francais',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 251),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 696,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Russian',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 255),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 744,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Polish',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 269),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 792,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Spanish',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 254),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 840,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Mandarin',
                        style: TextStyle(
                          color: Color(0xFF202244),
                          fontSize: 15,
                          fontFamily: 'Mulish',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      const SizedBox(width: 243),
                      Container(
                        width: 28,
                        height: 28,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE8F1FF),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 2, color: Color(0xFFB4BDC4)),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 428,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 389.33,
                        top: 17.33,
                        child: Container(
                          width: 24.33,
                          height: 11.33,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Opacity(
                                  opacity: 0.35,
                                  child: Container(
                                    width: 22,
                                    height: 11.33,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 1),
                                        borderRadius: BorderRadius.circular(2.67),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 2,
                                top: 2,
                                child: Container(
                                  width: 18,
                                  height: 7.33,
                                  decoration: ShapeDecoration(
                                    color: Colors.black,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(1.33),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 360.66,
                        top: 17.33,
                        child: Container(
                          width: 17.50,
                          height: 11,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/18x11"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 335.55,
                        top: 17.67,
                        child: Container(
                          width: 19.40,
                          height: 10.67,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/19x11"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 22,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 54,
                                child: Text(
                                  '9:41',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 15,
                                    fontFamily: 'Jost',
                                    fontWeight: FontWeight.w600,
                                    height: 0,
                                    letterSpacing: -0.30,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 892,
                child: Container(
                  width: 428,
                  height: 34,
                  padding: const EdgeInsets.only(
                    top: 10,
                    left: 147,
                    right: 147,
                    bottom: 19,
                  ),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 134,
                        height: 5,
                        decoration: ShapeDecoration(
                          color: Color(0xFFE2E6EA),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(100),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}